### ISSUE TITLE
Option to give Reply notifications a different sound

### ISSUE THREAD

**Issue by polychromia** [tateisu/SubwayTooter#113]
It would be nice if we could set a sound to Reply notifications that's different from Fav/Boost notifications - this way we could know which event we've received without looking at the screen.

**Comment by tateisu** [comment]
since from Android 8, notification sound is configurable in device's notification setting, per "notification channel".
currently ST make notification channel per account, because its tap action is open notification column for the account.

maybe I can add option to create another notification channel for reply, but it make notification grouping that separate reply and other notification.

(current)
- notification group for account A
- notification group for account B
- notification group for account C
- notification group for account D

(changed)
- notification group for account A : reply 
- notification group for account A : other
- notification group for account B : reply 
- notification group for account B : other
- notification group for account C : reply 
- notification group for account C : other
- notification group for account D : reply 
- notification group for account D : other

also, it make some difficulty in notification remove action and management of PendingIntent's requestCode.

I will continue to consider.

**Comment by tateisu** [comment]
implemented at 47661d235840f83ad034676c0b7c7e212b7a866a

**Comment by tateisu** [comment]
Released. https://github.com/tateisu/SubwayTooter/releases/tag/v3.8.7
sinse from 10/25, it move from beta track to product track on play store.

**Comment by polychromia** [comment]
Thank you :)
