### ISSUE TITLE
设置里添加“改变语言”下拉菜单

### ISSUE THREAD

**Issue by chinnux** [tateisu/SubwayTooter#154]
安装软件后在设置里找不到“改变语言”选项
希望在设置里添加“改变语言”下拉菜单

**Comment by tateisu** [comment]
他の多くのアプリと同様、このアプリは端末の言語の設定に従います。

UI言語をアプリ内部で切り替える特別なモチベーションを私は感じていません。

GmailやChromeがそれを持たないのに、STにそれが必要だと思う理由は何でしょうか？

**Comment by chinnux** [comment]
> 他の多くのアプリと同様、このアプリは端末の言語の設定に従います。
> 
> UI言語をアプリ内部で切り替える特別なモチベーションを私は感じていません。
> 
> GmailやChromeがそれを持たないのに、STにそれが必要だと思う理由は何でしょうか？

Thanks your reply ! I means subwaytooter can not change chinese in my phone ,I do not know why .😂😂

**Comment by tateisu** [comment]
if your device does not support some languages, it also makes difficult
that app uses those language with/without device's language setting.

the problem should be fixed by device user or maker, not a app author.

please try "more locale 2" to enable locales on your device.





2021年5月9日(日) 12:50 chinnux ***@***.***>:

**Comment by tateisu** [comment]
https://github.com/tateisu/SubwayTooter/commit/4ba61b86cef8d64b7f45d8436befbf00538a512e
