### ISSUE TITLE
Account auto login

### ISSUE THREAD

**Issue by mitchellurgero** [tateisu/SubwayTooter#99]
Looks like when using google smartscreen + data restore from google cloud, the app signs me in automatically, which is fine, but it does not reflect this autologin under the accounts settings.

**Comment by tateisu** [comment]
Since I am not familiar with SmartScreen, I do not fully understand the details of the defect and the expected behavior. Can you explain these?

ST itself does not care user's mail address, password, any 2FA information.
ST uses OAuth2 browser authentication and its login process is runs on web browser. 
when ST send OAuth2 login URL to web browser, append "force_login" parameter for multi account issue. the behavior of login page is mainly depends on Web browser and Mastodon's web page.
then ST saves access token to in app database. it will be backup,exported,imported.
